logging:
  level:
    com:
      example:
        mapper: debug

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml

server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    name: defaultDataSource
    password: 123456
    url: jdbc:mysql://localhost:3306/security_auth?serverTimezone=UTC
    username: root
  mail:
    host: smtp.163.com  #邮箱主机服务器
    password: xxxxxxxxx  #邮箱密码/调用密钥
    properties:
      from: xxx@163.com  #你的邮箱
    username: xxx@163.com  #你的邮箱
  redis:
    database: 0
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
